### ISSUE TITLE
Add a method for overriding App path

### ISSUE THREAD

**Issue by silverhammermba** [richardwilkes/toolkit#1]
I maintain the unofficial gcs package in the [AUR](https://aur.archlinux.org/packages/gcs/), and one of the difficulties I had with packaging according Arch's [Java package guidelines](https://wiki.archlinux.org/index.php/Java_package_guidelines) is that the jars are supposed to be placed in a separate directory from other application files.

Specifically all the jars go in `/usr/share/java/gcs` and the library goes in `/usr/share/gcs`. The problem with this is that the toolkit has a few hard-coded ways of deciding what the app path should be [App.java](https://github.com/richardwilkes/toolkit/blob/master/src/com/trollworks/toolkit/ui/App.java#L56) and none of them work with Arch's particular way of organizing java apps.

My solution was just to patch the toolkit to allow a simple override using an environment variable `path = Paths.get(System.getenv("GCS_HOME"));`. Would you be amenable to incorporating such a patch into the toolkit? I would submit a pull request but I'm not sure what the proper way would be to implement it since the toolkit is not GCS-specific.

**Comment by richardwilkes** [comment]
I guess I'm not understanding why you'd want to split things apart. Reading the link you gave for 'Java package guidelines', I noticed it states:

> As is standard with Arch Linux packages, if the above standards cannot be adhered to without a serious amount of work, the package should be installed in its preferred manner, with the resulting directory located in /opt. This is useful for programs that bundle JREs or include customized versions of dependencies, or do other strange or painful tasks.

So why not just install everything as-is into `/opt/gcs` ?

If what you are trying to do is just separate the GCS data files (i.e. those that are shipped in the `Library` tree), I could certainly accommodate that via an environment variable as that would only affect GCS and not other projects of mine. Currently, there are two places that look this location up, one on line 58 of ListCollectionThread.java and one on line 371 of SheetPreferences.java. It would be easy enough to create a method for obtaining the root of the library that allows an environment variable override and I'd be happy to do so if it made things better for you.

**Comment by silverhammermba** [comment]
I did consider throwing everything in `/opt`, but it was just a one-line patch to get an environment variable override working so I figured it was worth the effort to adhere to the more strict guidelines. You are correct that it just amounts to changing the location of the `Library` tree, so that would be an acceptable workaround.

Thanks for being so accommodating!

**Comment by richardwilkes** [comment]
I've checked in support for the `GCS_LIBRARY` environment variable override.

By default, GCS looks for its library of data files next to itself in its installation directory. You can now alter this behavior by setting the environment variable `GCS_LIBRARY` to point to some other location on disk instead.

[Commit b251cbc](https://github.com/richardwilkes/gcs/commit/b251cbcf3002d14df75eb4320bff7a807941a183)
